# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AB Ambassadors
description: > # this means to ignore newlines until "baseurl:"
  AB Ambassadors is an independent global tourism and hospitality advisory and asset management firm to help organizations achieve their goals by providing strategic guidance. The focused initiatives include addressing operations for optimum efficiency, maximizing revenue generation, and focused sales & marketing activities. Support areas and practice include leadership development, project master planning review, predevelopment analysis, due diligence, repositioning, food and beverage consulting, operator selection and asset management.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abambassadors.com" # the base hostname & protocol for your site

ab-email: me@abid-butt.com
abambassadors-linkedin: https://www.linkedin.com/company/ab-ambassadors/

ht-youtube: https://www.youtube.com/channel/UCVBfsbg4K5sq6aPljJdWDBg
ht-facebook: https://www.facebook.com/groups/hospitalitytalks/
ht-linkedin: https://www.linkedin.com/groups/10512845/
ht-podcast: https://podcasts.apple.com/us/podcast/hospitality-talks/id1558787121?uo=4
ht-spotify: https://open.spotify.com/show/1nKjEOtxeiqKXybs6tyATw

# Build settings
markdown: kramdown

collections:
  services:
    output: false
  
  hospitality-talks:
    output: false